import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'
import Header from "@/Components/Header";
import Cursor from "@/Components/Cursor";

const inter = Montserrat ({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Azizbek Jaksilikov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="box">
          <Cursor/>
          <div className="wrapper">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
